title: PSYC341
github_username: UMDOER
minimal_mistakes_skin: default
search: true

toc: true
toc_label: "Contents"

defaults:
  sidebar: true
  nav: "docs"
  
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-titles-from-headings
  
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
  
defaults:  
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      strip_title: true

